spring:
  application:
    name: Movieflix
  datasource:
    url: jdbc:mysql://localhost:3306/movieflix
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

project:
  poster: posters/